# Site settings
title: LauraSzyms on Learn.
header-img: img/home-bg.png
email: lauraszyms@gmail.com
copyright_name: lauraszyms
description: > # this means to ignore newlines until "baseurl:"
  Coding Blog Posts.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lauraszyms
learn_profile: lauraszyms
email_username: lauraszyms@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
